Repository 0xhiro/amongrust, pull requests merged in 2022-11, with the labels that each got.

#4 Fem amogus
  Cargo.toml
  src/main.rs
Labels: enhancement, very sus

#9 merge staging
  Cargo.toml
  src/main.rs
Labels: enhancement

#3 amogus
  Cargo.lock
  Cargo.toml
  src/main.rs
Labels: enhancement, good first issue, sus
